language: node_js
node_js:
- '0.11'
- '0.10'
before_script:
- npm install -g gulp
- npm install
script: gulp build
after_success:
- bash ./deploy.sh
branches:
  only: master
env:
  global:
  - secure: Q292RuRfWnEN+UDxWVptOiLbQ1kUaP6dRW5ndAY83SGLKG6eGAD2hQjzpBfBtuCFxvmFecWUQfWj4m2rJtNC3OFnEFN4oV5TKUwsr2VEDLVetNtjRhZt4JaQtHeK99DddTR6COAp4ay4w16eBX+ZZ8cNPp0HJCNIjbyyNy/OX7QIWdWsl/Y23fpbga6Aom0o3+iQyk6if4JvSzY8sEuipS10g4UkducmuCipLWvBSun+F3hDMV2m+1xAcYjoropnasCWbbXMOcUMIiSwZSIAoRxnC/jEpJVuGSJWyMJmulmle1FlzeQ5PsQ8uG1mjIBd5grhGlhEjK9hK3p00gSfZhC/oX/iGdLeMkWoGl79T0cYLRY9M1EU0DQ/VyQc3NhrWNpZr/Hs+sx8s8tZwJpbI82LCRbdd3HKDCqcnbc4W9uUAdL5+LyUltboLGVScPCoM0DqhFlrPxwYfz46TAUzqr+TJ9EYG1PrN4V2Zk2R8R38kAYc9JjE7wkQDsmnBbE3mNC3WRhfVUaxYWp8A2S+WlPY/Z8X7GKOfVfKhP+a8O6nbkWinPVFudcbYp0d93EfpJl+0EIZoj/sdltNQi0CwbOfHCnbj/dyvP1GX8ZdhG32XaTVbpdA9it4FIFSg/wQcXxPhAvygE6wJyPK5co1pQljGEiA/757qqfsNiHQdcE=
